name: Backend Deploy Workflow
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: 

env:
  SSH_KEY_PATH: "$HOME/.ssh/instance-key-pair.pem"

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v5
        with:
            fetch-depth: '0'
      - name: Detect Changed Paths
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            backend:
                - 'Backend/**'
            deps:
                - 'Backend/package.json'
                - 'Backend/pnpm-lock.yaml'

    # Skip everything if no backend files changed
      - name: No backend changes — skipping deployment
        if: steps.filter.outputs.backend == 'false'
        run: |
          echo "No changes detected in Backend/. Skipping deployment."
          exit 0

      - name: Save the SSH key
        if: steps.filter.outputs.backend == 'true'
        run: |
            mkdir -p ~/.ssh
            echo "[INFO] Saving SSH Key..."
            cat > "${{env.SSH_KEY_PATH}}" <<EOF
            ${{secrets.AWS_INSTANCE_KEY_PAIR}}
            EOF
            chmod 600 ${{env.SSH_KEY_PATH}}

      - name: SSH into backend server
        if: steps.filter.outputs.backend == 'true'
        run: | 
            ssh -o StrictHostKeyChecking=no -i "${{env.SSH_KEY_PATH}}" ubuntu@storra-backend.servehttp.com 'bash -se' <<'EOF'
            
            # -e: exit when error occurs
            # -u: not defined variable usage will be treated as error
            # -o pipefail: if a pipeline fails then whole pipeline will be treated as failed
            set -Eeuo pipefail

            export PNPM_HOME="$HOME/.local/share/pnpm"
            export NODE_BIN_DIR=/home/ubuntu/.nvm/versions/node/v24.15.0/bin
            export PATH="$PNPM_HOME:$NODE_BIN_DIR:$PATH"

            REPO_DIR="$HOME/Storra"
            BACKEND_DIR="$REPO_DIR/Backend"
            LOG_DIR="$HOME/deploy-logs"
            LOG_FILE="$LOG_DIR/storraBackend-$(date +%Y%m%d-%H%M%S).log"

            # all log files will go to this directory
            mkdir -p "$LOG_DIR"

            # all error/log will be written to this file
            exec >>"$LOG_FILE" 2>&1

            on_error() {
            local exit_code=$?
            local line_no=$1
            echo "[ERROR] Deployment failed at line $line_no with exit code $exit_code"
            exit "$exit_code"
            }
            trap 'on_error $LINENO' ERR

            echo "[INFO] Starting deployment at $(date -Is)"

            cd "$REPO_DIR"
            
            echo "[INFO] Pulling Latest changes from Github..."
            git fetch origin main
            git reset --hard origin/main

            if [ "${{steps.filter.outputs.deps}}" = "true" ]; then
                echo "[INFO] package manifest changed, running pnpm install..."
                cd "$BACKEND_DIR"
                pnpm install --frozen-lockfile
                cd "$REPO_DIR"
            fi

            pm2 reload storraBackend --update-env 
            echo "[INFO] Server deployed successfully at $(date -Is)"

            EOF